### ISSUE TITLE
Error with build, missing binary?

### ISSUE THREAD

**Issue by johnpetersjr** [ulver2812/aws-s3-backup#6]
Tried to download and install this today, got this error message:

Error output:
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-electron-v2.0-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.7 and electron@2.0.8 (electron-v2.0 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and electron@2.0.8 (electron-v2.0 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Connection closed while downloading tarball file 
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 

I'm guessing some binary is missing from S3?

**Comment by ulver2812** [comment]
Hi, sorry for the delay, I didn't receive any notification from github about this issue 🤔.
Anyway, you are trying to clone the repo and build the project on your own or you are trying to install the executable file on Windows ?

I need more information to understand what is going wrong here...

**Comment by johnpetersjr** [comment]
Here is the output from npm install - sanitized a little for folder names, etc.  Maybe you can see what is going wrong... I'm running this on MacOS 10.13.6 , npm version 6.13.6

```aws-s3-backup $ npm install

> aws-s3-backup@1.6.0 postinstall 
> npm run postinstall:electron && npx electron-builder install-app-deps


> aws-s3-backup@1.6.0 postinstall:electron 
> node postinstall

  • electron-builder version=20.28.1
  • loaded configuration file=electron-builder.json
  • rebuilding native production dependencies platform=darwin arch=x64
Error: /usr/local/Cellar/node/11.14.0/bin/node exited with code 1
Output:

> fsevents@1.2.7 install node_modules/fsevents
> node install

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
Failed to execute '/usr/local/Cellar/node/11.14.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=node_modules/fsevents/lib/binding/Release/electron-v2.0-darwin-x64/fse.node --module_name=fse --module_path=node_modules/fsevents/lib/binding/Release/electron-v2.0-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
  COPY node_modules/fsevents/lib/binding/Release/electron-v2.0-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

Error output:
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-electron-v2.0-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.7 and electron@2.0.8 (electron-v2.0 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and electron@2.0.8 (electron-v2.0 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Connection closed while downloading tarball file 
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/11.14.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=node_modules/fsevents/lib/binding/Release/electron-v2.0-darwin-x64/fse.node" "--module_name=fse" "--module_path=node_modules/fsevents/lib/binding/Release/electron-v2.0-darwin-x64" "--napi_version=4" "--node_abi_napi=napi"
gyp ERR! cwd node_modules/fsevents
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/11.14.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=node_modules/fsevents/lib/binding/Release/electron-v2.0-darwin-x64/fse.node --module_name=fse --module_path=node_modules/fsevents/lib/binding/Release/electron-v2.0-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:999:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/11.14.0/bin/node" "node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd node_modules/fsevents
node-pre-gyp ERR! node -v v11.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fsevents@1.2.7 install: `node install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.2.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2020-02-13T16_42_30_648Z-debug.log
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreServices.framework/CoreServices.tbd and library file /System/Library/Frameworks//CoreServices.framework/CoreServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork.tbd and library file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList are out of sync. Falling back to library file for linking.

    at ChildProcess.childProcess.once.code (node_modules/builder-util/src/util.ts:254:14)
    at Object.onceWrapper (events.js:281:20)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Socket.stream.socket.on (internal/child_process.js:403:11)
    at Socket.emit (events.js:193:13)
    at Pipe._handle.close (net.js:614:12)
From previous event:
    at rebuild (node_modules/app-builder-lib/out/util/yarn.js:239:18)
    at node_modules/app-builder-lib/src/util/yarn.ts:20:11
From previous event:
    at installOrRebuild (node_modules/app-builder-lib/out/util/yarn.js:68:17)
    at node_modules/electron-builder/src/cli/install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
From previous event:
    at installAppDeps (node_modules/electron-builder/out/cli/install-app-deps.js:174:17)
    at then (node_modules/electron-builder/src/cli/cli.ts:42:48)
    at processImmediate (internal/timers.js:443:21)
From previous event:
    at Object.args [as handler] (node_modules/electron-builder/src/cli/cli.ts:42:48)
    at Object.runCommand (node_modules/electron-builder/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (node_modules/electron-builder/node_modules/yargs/yargs.js:1063:30)
    at Object.get [as argv] (node_modules/electron-builder/node_modules/yargs/yargs.js:1004:21)
    at Object.<anonymous> (node_modules/electron-builder/src/cli/cli.ts:25:28)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at findNodeScript.then.existing (node_modules/npx/node_modules/libnpx/index.js:268:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-s3-backup@1.6.0 postinstall: `npm run postinstall:electron && npx electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aws-s3-backup@1.6.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .npm/_logs/2020-02-13T16_42_31_277Z-debug.log
```

**Comment by nathanielrindlaub** [comment]
I just attempted to clone and build on Mac OS 10.14.6, npm 6.11.3, node v12.12.0, and ran into similar npm install issues. Seems like a great tool any help getting it up and running would be much appreciated.

**Comment by ulver2812** [comment]
Hi, the problem is related to fsevents as you can see here:

https://github.com/fsevents/fsevents/issues/181

The solution is to use the latest version of fsevents, you can do this by cloning the repo, add this dependency in the package.json

`"fsevents": "^2.1.2"`

and then run

`npm i`

An alternative is to clone the repo and run the following commands sequentially:

```
npm i fsevents@latest
npm i
```

This should solve the issue, let me know if it's all ok.

**Comment by nathanielrindlaub** [comment]
Thanks @ulver2812, that got me a little closer. Npm install still failed for me after the fsevents update, and it seemed to be related to an old version node-gyp that was requested by angular-devkit/build-angular. I unpinned the angular-devkit/build angular to pull the latest version, reinstalled all the dependencies, and that worked without throwing errors. 

However, when I tried 

```npm run electron:local```

I got different errors, seemingly related to angular-cli:

```
Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber.project (/path/to/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/workspace/workspace.js:210:42)
```

**Comment by ulver2812** [comment]
Hi @nathanielrindlaub , I have tried the solution posted above on:
- macOS 10.14.3
- Node v 10.11.0
- Npm v 6.4.1

Following those steps:
- Clone the repo
- Run:
```
npm i fsevents@latest
npm i
npm run electron:local
```

And didn't get any error, can you confirm that you have followed the above steps in a newly cloned repo ?

Take a look at the screen.
![Screenshot-2020-02-18-at-09 32 01](https://user-images.githubusercontent.com/25301598/74718354-579d7200-5232-11ea-8d0e-970e3ba0a79e.jpg)

**Comment by johnpetersjr** [comment]
> npm i fsevents@latest
> npm i
> npm run electron:local

I followed the above steps, and it is working for me now.  Thank you!

npm 6.13.6
node 11.14.0
macOs 10.13.6

Not sure if I should close this issue/question since you have another customer still pending?

**Comment by ulver2812** [comment]
@johnpetersjr , it's better to wait the @nathanielrindlaub response. If it's all ok I can commit a fix and close the issue.

**Comment by nathanielrindlaub** [comment]
Hey @ulver2812 - followed your steps and got the following error on the last npm install step:

```
../src/create_string.cpp:17:25: error: no matching constructor for initialization of 'v8::String::Utf8Value'
  v8::String::Utf8Value string(value);
                        ^      ~~~~~
/Users/nathaniel.rindlaub/.node-gyp/12.12.0/include/node/v8.h:3046:5: note: candidate constructor not viable: no known conversion from
      'v8::Local<v8::Value>' to 'const v8::String::Utf8Value' for 1st argument
    Utf8Value(const Utf8Value&) = delete;
    ^
/Users/nathaniel.rindlaub/.node-gyp/12.12.0/include/node/v8.h:3039:5: note: candidate constructor not viable: requires 2 arguments, but
      1 was provided
    Utf8Value(Isolate* isolate, Local<v8::Value> obj);
    ^
1 error generated.
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/nathaniel.rindlaub/Documents/Experiments/aws-s3-backup/aws-s3-backup/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/nathaniel.rindlaub/.nvm/versions/node/v12.12.0/bin/node" "/Users/nathaniel.rindlaub/Documents/Experiments/aws-s3-backup/aws-s3-backup/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/nathaniel.rindlaub/Documents/Experiments/aws-s3-backup/aws-s3-backup/node_modules/node-sass
gyp ERR! node -v v12.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
```

I think the issue maybe occurs when you're trying to run later versions of node (I'm on 12.12.0 and it appears you guys are on 10.x and 11.x). If you upgrade node, does the npm install still work for you?

**Comment by ulver2812** [comment]
@nathanielrindlaub , I'm sorry but I can't try to use different version of node now. 
You can try on your own by using nvm:
https://github.com/nvm-sh/nvm

Similar issue here: https://github.com/nodejs/node-gyp/issues/1941

I'm pretty sure that there's an incompatibility with node 12, unfortunately I'm to busy now, I can't update the project, but the solution to build the app on your own is pretty easy, use nvm to switch temporarily on node 11.

Let me know if it works so I can close the issue, thanks.
